apiVersion: v1
kind: Service
metadata:
  name: log-app-service
spec:
  type: LoadBalancer      # localhost에서 접속
  selector:
    app: log-app
  ports:
    - protocol: TCP
      port: 8081          # 브라우저 포트
      targetPort: 8081    # 컨테이너 내부 포트