services:
  logcollector-db:
    image: mariadb:latest
    container_name: logcollector-mariadb
    environment:
      MARIADB_DATABASE: logcollector
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$${MARIADB_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - logcollector-db-data:/var/lib/mysql

  logcollector-redis:
    image: redis:7-alpine
    container_name: logcollector-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - logcollector-redis-data:/data

volumes:
  logcollector-db-data:
  logcollector-redis-data:
