services:
  logcollector-db:
    image: mariadb:latest
    container_name: logcollector-mariadb
    environment:
      MARIADB_DATABASE: logcollector
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$${MARIADB_ROOT_PASSWORD} --silent" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - logcollector-db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro

  logcollector-redis:
    image: redis:7-alpine
    container_name: logcollector-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - logcollector-redis-data:/data

  # elasticsearch:  # v.1에서는 ES 제외
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
  #   container_name: logcollector-es
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - es-data:/usr/share/elasticsearch/data

  prometheus:
    image: prom/prometheus:latest
    container_name: lc-prometheus.yml
    volumes:
      - ../../docs/monitoring/datasource/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: lc-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  logcollector-db-data:
  logcollector-redis-data:
  # es-data:
