apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      containers:
        - name: log-app
          image: logcollector-log-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: TZ
              value: Asia/Seoul

            - name: SPRING_PROFILES_ACTIVE
              value: docker

            # JVM 힙 제한 (OOM Kill 방지)
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms256m -Xmx512m"

            # LC DB 연결 설정
            - name: SPRING_LC_DATASOURCE_URL
              value: jdbc:mariadb://logcollector-db:3306/logcollector?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_LC_DATASOURCE_USERNAME
              value: root
            - name: SPRING_LC_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logcollector-secrets
                  key: db-root-password

            # KB DB 연결 설정
            - name: SPRING_KB_DATASOURCE_URL
              value: jdbc:mariadb://logcollector-db:3306/knowledge_base?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_KB_DATASOURCE_USERNAME
              value: root
            - name: SPRING_KB_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logcollector-secrets
                  key: db-root-password

            # Redis 설정
            - name: SPRING_REDIS_HOST
              value: lc-redis-master

            # OpenAI API Key
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: logcollector-secrets
                  key: openai-api-key

            # ES 추가
            - name: ES_HOST
              value: "logcollector-es"
            - name: ES_PORT
              value: "9200"
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1Gi"