apiVersion: apps/v1
kind: Deployment
metadata:
  name: logcollector-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: soyunju/logcollector-es-nori:8.15.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"
            # ES 힙 직접 제한 (노드 메모리 부족으로 OOM Kill 방지)
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
          resources:
            requests:
              memory: "1.5Gi"
            limits:
              memory: "2Gi"